### ISSUE TITLE
Good project

### ISSUE THREAD

**Issue by OttoKlaasen** [agrimpelhuber/esp8266-tvbgone#1]
Great project,
I used an ESP32 and after modifying the PINS it worked fine on a Philips and Panasonic TV, only my Wife did not like it when i tested it.
Followings pins settings work for ESP32: 

// What pins do what
#define LED GPIO_NUM_22
#define IRLED GPIO_NUM_21
#define TRIGGER GPIO_NUM_16
#define REGIONSWITCH GPIO_NUM_17

Also forced the code to be compiled in PlatformIO, just move all subroutines above the Setup() as required for PlatformIO.

**Comment by agrimpelhuber** [comment]
Thanks for the feedback. Closed because your wife cannot be made into a project issue 😜
