### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by rustb0ne** [agrimpelhuber/esp8266-tvbgone#2]
Can someone give me graphical wiring scheme? Author's instruction makes me confused

**Comment by agrimpelhuber** [comment]
Sorry, can't do it any more. The hardware has long been used in another project.

Which brings me to the main point: there is nothing fancy about the wiring. Just switches and IR diodes. Google brings up loads of wiring instructions to connect them to the esp8266, including the necessary resistors and stuff.

I remember I used 3 diodes for more output, but I would need to Google myself how to wire them - parallel, serial, how to determine resistance (if any)

**Comment by agrimpelhuber** [comment]
Closed because I'm arching this project
